version: '3.7'
services:
    db:
        build:
            context: mysql
            dockerfile: Dockerfile
        environment:
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - '3306:3306'
    go:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
